version: '3.7'
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'lumen_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: